### ISSUE TITLE
Maybe bug

### ISSUE THREAD

**Issue by hyochan** [impin2rex/insta-reel#1]
Hello, I tried your parser today and see the below error so I hope this can help you.

```
/node-test/node_modules/insta-reel/insta-reel.js:26
  } = JSON.parse(/window\._sharedData = (.+);/g.exec(script)[1]);
                                                            ^

TypeError: Cannot read properties of null (reading '1')
    at instaReel (/home/hyo/Github/hyochan/node-test/node_modules/insta-reel/insta-reel.js:26:61)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/hyo/Github/hyochan/node-test/index.js:4:18
```

**Comment by impin2rex** [comment]
Instagram now protected the reel's shareable link.
That's why the error comes in. 

You have to bind your account. @hyochan 
![Screenshot 2022-01-21 at 1 33 34 PM](https://user-images.githubusercontent.com/53005904/150489493-fd667c5e-bcb8-4228-baa0-e49152e1ac5b.png)

**Comment by codedrishti** [comment]
How can I resolve this, Is there any documentation regarding this issue then please share it. Help is appreciatable and thank you.
